import '@/styles/globals.css'
import Head from 'next/head'
import { Inter } from '@next/font/google'
import NextNProgress from 'nextjs-progressbar'

const inter = Inter({ subsets: ['latin'] })

export default function App({ Component, pageProps, router }) {
  const getLayout = Component.getLayout || ((page) => page)
  return (
    <>
      <Head>
        <title>YouFeel</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <style jsx global>{`
        html, body, p {
          font-family: ${inter.style.fontFamily};
        }
      `}
      </style>
      <NextNProgress
        height={2.5}
        color='rgb(251 113 133)'
        options={{ minimum: 0.8 }}
      />
      {getLayout(<Component {...pageProps} />)}
    </>
  )
}
